# Generated by Django 2.1.7 on 2019-12-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='port',
            field=models.CharField(max_length=50),
        ),
    ]
